// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW7XHTOJomVlKXZlgD7nnw0X6GMF5BlFk',
    appId: '1:429856852844:web:d21d0b224a9fd6ff750149',
    messagingSenderId: '429856852844',
    projectId: 'ngo-connect-2f9a6',
    authDomain: 'ngo-connect-2f9a6.firebaseapp.com',
    storageBucket: 'ngo-connect-2f9a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU9gkwWZ-Off-fQYF55PDYuplCab7X6_Q',
    appId: '1:429856852844:android:40cda19fdbb7e2f2750149',
    messagingSenderId: '429856852844',
    projectId: 'ngo-connect-2f9a6',
    storageBucket: 'ngo-connect-2f9a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI4A7lNf4gEY_mIXUAqyGNFqKTMyohxkg',
    appId: '1:429856852844:ios:a3ffee3a5e88dc0a750149',
    messagingSenderId: '429856852844',
    projectId: 'ngo-connect-2f9a6',
    storageBucket: 'ngo-connect-2f9a6.appspot.com',
    iosClientId: '429856852844-sr3bv0dikr8vd0dh2t72ge33f7pumb3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngoConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI4A7lNf4gEY_mIXUAqyGNFqKTMyohxkg',
    appId: '1:429856852844:ios:0afe4b4685b7341f750149',
    messagingSenderId: '429856852844',
    projectId: 'ngo-connect-2f9a6',
    storageBucket: 'ngo-connect-2f9a6.appspot.com',
    iosClientId: '429856852844-b41fgo367jdte1sqp687i55t7lv4gaqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngoConnect.RunnerTests',
  );
}
